### ISSUE TITLE
C++ Scalfolding Bug 

### ISSUE THREAD

**Issue by busmanl30** [djkaty/Il2CppInspector#113]
I keep getting these errors ALL THE TIME when i compile and its very annoying
![Screenshot (1)](https://user-images.githubusercontent.com/31174884/102536148-363a2c00-4077-11eb-9938-35d08ae2549a.png)

**Comment by djkaty** [comment]
The enum error is a result of using the wrong toolchain.

From the readme:

"Compatibility: It is recommended to use Visual Studio 2019 (MSVC++ Build Tools v142 or later). The scaffolding projects have been tested with Visual Studio 2019 and Visual Studio 2017 (MSVC++ Build Tools v141), however some helper code is omitted when using Visual Studio 2017 in order to enable compilation to succeed."

Full tutorial: https://katyscode.wordpress.com/2020/11/27/il2cppinspector-tutorial-how-to-create-use-and-debug-il2cpp-dll-injection-projects/

Note from the tutorial:

"Note: It is strongly recommended to use Visual Studio 2019 and the MSVC++ Build Tools v142 with Windows 10 SDK when working with Il2CppInspector C++ scaffolding projects."

There are some other known issues with scaffolding that I haven't addressed yet, but try those tips first and let me know how you get on!

**Comment by busmanl30** [comment]
i tried to retarget, and i dont see anything about MSVC++ v142

**Comment by djkaty** [comment]
![image](https://user-images.githubusercontent.com/4500319/102562188-d1aeb980-40d6-11eb-84f8-2a57babb294b.png)

It should be in your project properties. Select Windows SDK '10.0' and Platform Toolset 'Visual Studio 2019 (v142)'.

**Comment by vaverix** [comment]
I've had the same problem with 64bit DLL. Go to the "il2cpp-types.h" and replace all occurrences of "int32_t" to "int64_t" and let me know if it worked for you.

**Comment by busmanl30** [comment]
I’m on a 64 bit, I just ignored it and fixed it, they just happen to show up after I had a small include error

**Comment by djkaty** [comment]
@vaverix @busmanl30 if either of you guys have found bugs, please let me know with full details so I can commit fixes :)

**Comment by djkaty** [comment]
Closing, no response from OP.
