### ISSUE TITLE
Error Wild Rift and Honkai Impact 3rd

### ISSUE THREAD

**Issue by FussyCone** [djkaty/Il2CppInspector#126]
I have a problem with the game Honkai Impact 3rd, it is in version 4.5 PC / Android. The Plugin doesn't give me option 4.5, only 4.3. But I tried, I put UnityPlayer.dll from the 4.5 PC version and the global-metadata or apk from the Android version 4.5. Then the Decrypting Metadata screen appeared and after a few seconds the program crashes.
And another problem is with Wild Rift, I read a closed topic from a user with the same problem that I'm having an error message:

"The detected ll2CppCodeRegistration / ll2CppMetadataRegistration structs do not pass validation.
this may mean that their fields have been re-ordered as a form of obfuscation - this scenario is not currently supported by ll2CppInspector. consider re-ordering the fields in ll2CppBinaryClasses.cs and try again. "

I did a git clone project, compiled but didn't understand which commit fixes this problem

**Comment by djkaty** [comment]
You can try the 3.8 or 4.3 DLLs as they are interchangeable, with the 4.5 global-metadata.dat. If that doesn't work I can update it when I have chance, but I will say that plugin is only meant to be an example and I won't update it forevermore. The source code is fully documented and I wrote an extremely extensive 4-part guide on how to reverse engineer it here: https://katyscode.wordpress.com/2021/01/17/reverse-engineering-adventures-honkai-impact-3rd-houkai-3-il2cpp-part-1/ - so people should preferably PR changes to the plugin to update it for new versions.

The latest commit should work just fine with Wild Rift, make sure you have all four core plugins enabled otherwise it will fail. If it still doesn't work, it's possible they changed something so feel free to send over the metadata and binary files :)

**Comment by djkaty** [comment]
Okay, as it happens there was actually a bug in the plugin, I've fixed it and it works with 4.5 now. You will need to build the plugin yourself from the plugins repository until the next release is pushed.

**Comment by FussyCone** [comment]
Thanks, It worked. Only Wild Rift I did not understand which commit you referred to when saying "The latest commit" and yes i
have all four core plugins enabled. The part of the commit that I didn't understand which commit fixes the Wild Rift Problem

**Comment by djkaty** [comment]
Wild Rift was fixed before Christmas; if it still doesn't work I'll need you to send over the files so I can take a look!

**Comment by djkaty** [comment]
Closing - feel free to re-open if you're still experiencing issues!
