### ISSUE TITLE
--suppress-metadata still yielding type indices

### ISSUE THREAD

**Issue by RaenonX** [djkaty/Il2CppInspector#127]
### Bug description

Using CLI, type indices are still emitted even if the flag `--suppress-metadata` is specified. (At least for Dragalia Lost)

[This][commit] is the diff between the dump of v2.2.0 and v2.3.0.

[commit]: https://github.com/RaenonX-DL/dragalia-decompile/commit/9cb0c46aa6120a32638232264d4990858bfd189d

### Steps to reproduce

1. Try to dump the libil2cpp. Dragalia Lost v2.2.0 and upload the dump results to Github.
   - The `libil2cpp.so` for v2.2.0 can be found [here][v2.2.0].
2. Try to dump the libil2cpp.so of Dragalia Lost v2.3.0 and upload the dump results to Github
   - The `libil2cpp.so` for v2.3.0 can be found [here][v2.3.0].
3. Check the commit diff.

> The workflow I used can be found [here][gha]. I tried executing this locally. The results are the same.

Note: I use `dump-metadata.exe` in [my repository][my-repo] to dump the metadata, then input it to this IL2CPP dumper.

[my-repo]: https://github.com/RaenonX-DL/dragalia-decompile
[gha]: https://github.com/RaenonX-DL/dragalia-decompile/blob/main/.github/workflows/decompile.yml
[v2.2.0]: https://github.com/RaenonX-DL/dragalia-decompile/blob/main/Archive/v2.2.0.zip
[v2.3.0]: https://github.com/RaenonX-DL/dragalia-decompile/blob/main/Archive/v2.3.0.zip

**Comment by RaenonX** [comment]
In case you need to find where it is, here's the line that generates the type indices (where I think it should not if suppressed)

https://github.com/djkaty/Il2CppInspector/blob/e2c17ec442ec00b41e4e61d705c0eaeff88d54ec/Il2CppInspector.Common/Outputs/CSharpCodeStubs.cs#L354

**Comment by djkaty** [comment]
I already fixed it for you, hold on :D

**Comment by RaenonX** [comment]
> I already fixed it for you, hold on :D

I was going to fix that, nvm thanks! May I grab the release build once you've completed that? We're expected to have an update on Jan.25, I hope I can do some comparison before that.

**Comment by djkaty** [comment]
This issue is now fixed in https://github.com/djkaty/Il2CppInspector/commit/61bd7637c6586ba7955dd0f7859886c33b4cd38a :) Good catch and thank for the clear bug explanation which let me fix it very fast.

Just a note: il2cpp-dumper and il2cppinspector are two different projects by different authors, you are using the latter of the two (my tool) :) Also I don't know what dump-metadata.exe does since there was no source code for it in your repo, but if you're interested, the latest builds of Il2CppInspector have a plugin system which allows you to edit the behaviour of the load pipeline so you could include the code as a plugin. Optionally if you wish to share, you can also upload it to the plugins repo as a PR and we can include it as a submodule in future releases. If there are missing features that prevent you from being able to create a plugin the way you want, I would love to hear about them. Hope that helps!

**Comment by djkaty** [comment]
Did you mean you need me to upload the exe for you?

**Comment by RaenonX** [comment]
> This issue is now fixed in [61bd763](https://github.com/djkaty/Il2CppInspector/commit/61bd7637c6586ba7955dd0f7859886c33b4cd38a) :) Good catch and thank for the clear bug explanation which let me fix it very fast.
> 
> Just a note: il2cpp-dumper and il2cppinspector are two different projects by different authors, you are using the latter of the two (my tool) :) Also I don't know what dump-metadata.exe does since there was no source code for it in your repo, but if you're interested, the latest builds of Il2CppInspector have a plugin system which allows you to edit the behaviour of the load pipeline so you could include the code as a plugin. Optionally if you wish to share, you can also upload it to the plugins repo as a PR and we can include it as a submodule in future releases. If there are missing features that prevent you from being able to create a plugin the way you want, I would love to hear about them. Hope that helps!

### Naming

Oops, never know that, I'll fix the naming now (I may re-upload the whole repository and some permalink here will go invalid).

### `dump-metadata.exe`

Here's the [link][coneshell] to the source code of that (yeah pretty simple). I may not have enough time to create a plugin, but I will leave it here and let anyone interested in that to create such a plugin.

[coneshell]: https://gist.github.com/esterTion/7fde10f2cb02722079d5fd9335ad5848

**Comment by RaenonX** [comment]
> Did you mean you need me to upload the exe for you?

Yes!

**Comment by RaenonX** [comment]
And thanks for being lightning-fast for fixing that, I was not expected such a speed 👍

**Comment by djkaty** [comment]
https://drive.google.com/file/d/1eg2zN_2tlBuhaUtOifEbAg8mQ0O1WVE8/view?usp=sharing

You were lucky, I just happened to be fixing another issue so I thought I'd kill two birds with one stone. I'm not normally this fast, but if you have any other issues I do usually reply within a couple of days :)

**Comment by RaenonX** [comment]
This one doesn't seem to work without plugin folders (and the size grows 2x comparing to the one I downloaded via Release). Is the plugin folder now a required parameter?

**Comment by RaenonX** [comment]
> https://drive.google.com/file/d/1eg2zN_2tlBuhaUtOifEbAg8mQ0O1WVE8/view?usp=sharing
> 
> You were lucky, I just happened to be fixing another issue so I thought I'd kill two birds with one stone. I'm not normally this fast, but if you have any other issues I do usually reply within a couple of days :)

Glad that I am lucky 😄 Just to let you know that this one works, thanks!

**Comment by djkaty** [comment]
Quick note: I made a debug build so that's why it's larger, although unfortunately the 2021.1 release exe's are going to be much larger than 2020.2.1 because we compile in the .NET base class library so that plugins can use it without having to include loads of .NET DLLs. Previously unused types were trimmed. This created all sorts of issues with plugins so I just gave up and disabled trimming.

The plugins folder is required yes, because some functionality was abstracted into plugins. You can just use one of the two `get-plugins` scripts to fetch them although you probably already figured that out. The release will include them as a bundle so it'll just be a case of unzip and go.

Have a great weekend!
