### ISSUE TITLE
Striped XOR encryption not work on new version of this game

### ISSUE THREAD

**Issue by ngoalong123** [djkaty/Il2CppInspector#135]
[This game have a update to day](https://play.google.com/store/apps/details?id=com.dts.freefireth)
Maybe tencent changed protect.
binary: https://drive.google.com/file/d/1pxU_Yd1EApvafAIQAFc66n-9tMkFm6Q1/view?usp=sharing
metadata: https://drive.google.com/file/d/1gsiaLB6E2nN56J0Z90FKLUCvWEimJMoi/view?usp=sharing

**Comment by djkaty** [comment]
I believe we went over this 4 days ago in issue #132, and several times over email, but let's try one more time:

> The global-metadata.dat for this application is obfuscated and not supported by Il2CppInspector.
> 
> Il2CppInspector now includes a plugin architecture to enable 3rd party developers to implement loaders for obfuscated or encrypted workloads that are not supported directly. If you wish to, you can familiarize yourself with this and develop a plugin for the task. Documentation here: https://github.com/djkaty/Il2CppInspector/wiki/Plugins%3A-Getting-Started - examples here: https://github.com/djkaty/Il2CppInspectorPlugins. Feel free to submit your plugin to the plugins repo if you'd like it to be bundled with future releases.

I believe I've been quite clear with you on multiple occasions about this, but I'm going to spell it out one more final time for you:

1. I am not a game crack-producing factory
2. We have provided you with a significant amount of powerful tooling to be able to handle these workloads yourself, precisely to handle these scenarios and because it's not possible or reasonable for me to deal with every single product ever released
3. If you are too lazy to do anything by yourself, this is your problem. I recommend you educate yourself about reverse engineering or get a different hobby.

Please do not submit any more crack requests.
