### ISSUE TITLE
Support dumped .bin without ELF header

### ISSUE THREAD

**Issue by AndnixSH** [djkaty/Il2CppInspector#152]
I came across a game that wipes out ELF header on runtime when you dump lib file from memory, so that Il2Cpp can't be dumped. Is it possible to ignore broken header?

[files.zip](https://github.com/djkaty/Il2CppInspector/files/6254311/files.zip)

```
Il2CppInspector Command-Line Edition
Version 2020.2.1
(c) 2017-2021 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24,1
Unsupported executable file format
Analyze IL2CPP data: 6,13 sec
```

**Comment by djkaty** [comment]
Hmm, yeah, it's possible but really fiddly. You'd have to re-construct the section ranges I guess and add a loader that accepts those instead of an ELF header. Could also be done with a plugin that hooks PreProcessImage, and providing options to the user to enter section address ranges. Not something I'll implement myself unless it becomes a commonplace issue.

**Comment by AndnixSH** [comment]
No problem, I just figure out I can copy headers from encrypted lib
