### ISSUE TITLE
Could not determine the binary file format [PRX file format support]

### ISSUE THREAD

**Issue by GrzybDev** [djkaty/Il2CppInspector#21]
Hello,
I'm trying to use your tool on PS4 game called "Knowledge is Power". But it seems that it's not supported.

Relevant files: [Media.7z](https://drive.google.com/file/d/13a_9nEq2RXdPSAuzgyu1Xu2g1uQQ5pOk/view?usp=sharing)

**Comment by djkaty** [comment]
Hey there!

I'm not at all familiar with PS4 file formats but I Googled around and saw that the PRX files you sent are a customized version of the standard ELF binary format. It could be interesting to add support for these if there is demand.

In the meanwhile, have you tried using prxtool to convert the file to ELF before running it through Il2CppInspector? https://github.com/pspdev/prxtool/

Let me know how you get on :)

**Comment by GrzybDev** [comment]
Hey there!

I have trouble compiling that tool, but i'm assuming that it still won't work (it's made for PSP, not PS4, and they could be (and most probably are) implemented diffirently)

**Comment by GrzybDev** [comment]
Hey there!

Update:
I've managed to decrypt that prx file using [this tool](https://www17.zippyshare.com/v/EddWLlkH/file.html), and now your tool are displaying this error:
`Something went wrong! Exception was thrown by the target of an invocation`

[Here](https://drive.google.com/file/d/1aoXlGFDPjTh_nDgr0FuZXWRancwTvBFk/view?usp=sharing) i uploaded that decrypted `Il2CppUserAssemblies.prx` from `Media.7z` from my first post.

**Comment by djkaty** [comment]
Hey,

Thanks for the update! I have spent some hours looking over the hex dump and IDA disassembly of the files you sent. I found a compiled binary of prxtool and you were right, it didn't work. After looking around quite a bit I finally found the file format here: https://www.psxhax.com/threads/ps4-self-spkg-file-format-documentation-detailed-for-scene-devs.6636/

I got a similar error to the one you just posted when trying to be lazy and cut the non-ELF part of the header (the first 0x160 bytes - 0x20 for the header and 0x20 each for 10 segments). It is looking for section names but there are no sections in the file you sent, only segments; I assume this is some quirk of how the ps4 executable file format works because normal ELF files have a number of named sections.

I'll take a look at the tool and new files you linked this evening and get back to you tomorrow, thank you :) I don't know how easy or difficult it's going to be, but either way it's going to take a bit of time so hang in there :)

**Comment by djkaty** [comment]
I've successfully reverse engineered the "decrypted" (actually just rearranged) file output from unfself. I have had to think about how to make it work automatically but I have a solution. It will take me some time to implement. Once it's done I will look at implementing some equivalent of unfself so we have native sprx support 🙂

**Comment by GrzybDev** [comment]
Wow! Thank you for your work! Can't wait :)

**Comment by djkaty** [comment]
Try it now :) (with the output of unfself)

**Comment by GrzybDev** [comment]
It works! Thank you so much, you rock 🥇

**Comment by djkaty** [comment]
Awesome, glad to hear! I'm going to leave this issue open for the time being because I think it would be nice to add support for fSELF / PRX files natively. I'll write again when there is more to report on that!

**Comment by djkaty** [comment]
As of https://github.com/djkaty/Il2CppInspector/commit/b961db78f2b5d597684a6b1d2a1819da4352446e you should now be able to load a .prx file into Il2CppInspector directly without needing to use unfself first! Let me know if this works for you 🙂

**Comment by GrzybDev** [comment]
It works like a charm 👍 Thank you for your work ✌️

**Comment by djkaty** [comment]
Awesome! Closing issue 🙂

**Comment by bqio** [comment]
I have a problem with [that](https://anonfiles.com/D119j8K4o0/Modules_7z) files. (PS4)

**Comment by djkaty** [comment]
@bqio Please open a separate issue and describe the problem in full with what you are trying to do and any error message you receive. I did just try the files you attached in Il2CppInspector and it worked fine.
