### ISSUE TITLE
Machine readable format 

### ISSUE THREAD

**Issue by Ben3874** [djkaty/Il2CppInspector#22]
To make it easier to add more plugin outputs, I would suggest adding an output to a machine readable format, such as .json or flatbuffers. This would make writing plugins for programs a lot easier, instead of generating an entire .py script for IDA, instead you could parse the file .json or flatbuffer.
Asking for this because x64dbg uses compiled C/C++ for plugins, so its not easy to generate a x64dbg plugin automatically, I would be interested in making a PR for a x64dbg plugin if you did this.

**Comment by djkaty** [comment]
Hi Ben!

I had to read this a few times to fully understand what you meant. In terms of IDA, I assume you mean using a fixed static script that loads in JSON produced by the app? That's certainly possible, I honestly don't see any advantage in doing that over just producing a self-contained script except for the re-usability of the machine-readable file with other programs. In the end that really depends on where you want to locate the processing logic - in an Il2CppInspector output class in a .NET-compatible language, or in your own external code.

Il2CppInspector already includes a fairly extensive query API based on the .NET Reflection API to provide discoverability of the relationships and properties of any given item from the IL2CPP binary. If you output all of this as data, you will be outputting an enormous amount of (often useless) data and have to roll your own API to process it for each use case. The existing outputs are a good case in point: the analysis of the IL2CPP binary generates a lot of data, however the C# output only uses half of it and the IDA output uses a different 1/3rd of it + some overlap. A few data points aren't currently used at all. It depends what you want to do, basically.

Circling back to x64dbg, I will admit I don't really understand why it is any easier/harder to spit out a plugin from Il2CppInspector vs writing a static plugin that parses JSON. Either way you are essentially just doing text processing.

There are surely use cases for machine-readable output such as JSON though. This could be implemented either in the traditional way the current C# and IDA outputs are, or serialize methods could be added to each type in the Il2CppInspector.Reflection namespace, either directly or in a separate file using extension methods or by changing the types into partial classes and adding the Serializable attribute to them. It should not be too traumatic to write, however I'm not currently planning to do this myself. If anyone submits a PR to generate JSON output, I will of course welcome it 🙂

**Comment by nneonneo** [comment]
@Ben3874 FWIW, I had a go at using the C# API directly in #24, and it's pretty darn good. It's way better than parsing a pile of JSON (and you are much more likely to have everything available, vs JSON where the conversion could be lossy). 

It certainly would be nice to add JSON to decouple the Inspector from any downstream tools, but deciding on a format is not a trivial matter when the format is so complex. The hazard is that being complete enough to be useful would produce a JSON nearly as hard to work with as the metadata itself. So this does require a bit of thought before committing to a particular format, IMHO.

**Comment by Ben3874** [comment]
@nneonneo I have no doubt that the C# API is powerful, problem is that x64dbg uses C++ DLL's for plugins. 
Plugins can only be loaded with a restart of the program & would have to be recompiled every time a game is updated. You could generate a .cpp/.hpp file but it'd be rather inconvenient. Would be a lot nicer to make a x64dbg plugin that loads a file and ship that with Il2CppInspector. 

I would probably recommend something like FlatBuffers over Json for significantly better performance.

Mentioning IDA probably confused you both, was just trying to say the IDA output would be cleaner if you loaded metadata from a file, rather than baking it into the script.

**Comment by nneonneo** [comment]
Alternatively, a thought: could you write the plugin in managed C++, calling into C#? That could open up a lot of possibilities. For example it might be possible to bridge bidirectionally so that Il2CppInspector can examine the binary state in x64dbg. 

(Ironically, I suppose you could also contemplate simply converting Il2CppInspector itself with Il2Cpp to get an unmanaged binary, if managed code doesn’t work...)

By the way, not trying to shoot down the machine readable approach, I agree it would be nice to have. Just throwing out alternatives here. 

Robert

**Comment by djkaty** [comment]
Well let's not make things unnecessarily convoluted here for now 🙂

I was thinking about the fact your issue might be down to having to re-compile each time and I was assuming you could just put a run of il2cppinspector in the Makefile as a pre-build event. If I understand correctly, you want to be able to just leave a single x64dbg plugin 'installed' and change to different input files as new versions of the app you're reverse engineering are released, is that correct?

What I'm thinking about is making some kind of output that's tailored for such a plugin. A flat file containing data as you suggest, but specifically designed to be loaded into the plugin. Because as @nneonneo said, outputting a generic file with all of the available data is pretty unwieldy, and outputting a generic file with only selected data will inevitably leave out something that someone else wants down the line. So that brings us to... what is the minimal set of data you need to be able to accomplish what you want to do in your workflow? (while trying to also generalize to other users' possible use cases with the same plugin somewhat)

**Comment by Ben3874** [comment]
Oh I just realized that x64dbg supports scripts on top of plugins.
I guess I'll fork and work on a PR.

**Comment by djkaty** [comment]
Hey Ben,

Just wanted to circle back and check if this is something you're working on? No stress at all either way, just keeping tabs on who's doing what :)

**Comment by Ben3874** [comment]
Stopped working on it, il2cppdumper got updated and now generates structs for IDA, good enough for me.

**Comment by djkaty** [comment]
The latest commit now includes JSON metadata output with an address map for the binary, including some stuff not supported by Il2CppDumper. It doesn't come close to outputting all of the available data - see Outputs/JSONMetadata.cs if you would like to PR any modifications or extensions to the output. I implemented this because I'm adding Ghidra support and it has a limit on how long a Python file can be, so I'll be using the JSON as input. The IDA output will get re-factored also.

Specify --json-out (or -o) to change the default filename of `metadata.json`, or use the GUI 🙂
