### ISSUE TITLE
The given key 'mscorlib.dll' was not present in the dictionary

### ISSUE THREAD

**Issue by kritzl** [djkaty/Il2CppInspector#32]
can you explain to me, what this error stands for?
or how i could fix this?

**Comment by LiamRiddell** [comment]
@djkaty Any solution for this? I'm getting the same issue :)

**Comment by ouzis** [comment]
also im getting  the same issue

**Comment by djkaty** [comment]
Hi guys,

In order to be able to fix this I need samples of the files you're trying to process. Please attach global-metadata.dat and the il2cpp binary file/executable so I can take a look!

Please note that because of covid-19 I don't have much time to work on Il2CppInspector right now, however I am hoping to have the opportunity to go over all of the outstanding issues on the tracker (in chronological order) in the first half of June. Sorry for this delay but there's nothing I can really do about it.

Please attach your sample files (all three of you!) and I'll gladly look at them as soon as I'm able :)

**Comment by djkaty** [comment]
Closing this issue as no samples have been submitted so there is no way for me to investigate the bug.

Feel free to re-open the issue if you'd like to submit sample binaries and metadata 🙂

**Comment by reidemeister94** [comment]
Here is a sample where i get that error:

[dump.zip](https://github.com/djkaty/Il2CppInspector/files/4788611/dump.zip)


![screen](https://user-images.githubusercontent.com/28828348/84817327-09984f80-b015-11ea-8479-1260a1e17afe.PNG)

**Comment by djkaty** [comment]
@reidemeister94 Excellent thank you, I shall look at this hopefully tomorrow!

**Comment by djkaty** [comment]
As it happens this issue was just fixed by a commit from a PR - https://github.com/djkaty/Il2CppInspector/commit/c9d65e5f2de213838b1bf2b495a08ac90f1ee86a

Let me know if that fixes it for you guys 🙂

**Comment by reidemeister94** [comment]
It works like a charm! Thank you very much!
