### ISSUE TITLE
Issues handling dumped ELFs

### ISSUE THREAD

**Issue by kttyb0f** [djkaty/Il2CppInspector#44]
Hey, talking about a literal dump here where sections of the unpacked ELF are ripped from /proc/self/maps, then concatenated together according to the map's raw data offset. 

On this sample, il2cppinspector fails while processing relocations.... but I've seen other issues parsing the dumped ELF, I'll keep an eye out to collect those samples too.

```
---------------------------
Error
---------------------------
An item with the same key has already been added. Key: 18446744069414584320
---------------------------
OK   
---------------------------
```

Example libil2cpp.so here: https://files.catbox.moe/vcn5d1.zip 
CodeRegistration @ 066C7E08 (assume based at zero)
MetadataRegistration @ 066C7E78

e: here's globalmetadata as well,  https://files.catbox.moe/k6rexa.bin
and cli log
```
Il2CppInspector Command-Line Edition
Version 2020.1
(c) 2017-2020 Katy Coe - www.djkaty.com - www.github.com/djkaty

Detected metadata version 24.1
Processed 877968 relocations
Container format: ELF64
Container endianness: Little
Architecture word size: 64-bit
Instruction set: ARM64
Global offset: 0x0000000000000000
Symbol table(s) found with 156 entries
No matches in symbol table
Required structures acquired from code heuristics. Initialization function: 0x0000000001427BF8
CodeRegistration struct found at 0x00000000066C7E08 (file offset 0x066B7E08)
MetadataRegistration struct found at 0x00000000066C7E78 (file offset 0x066B7E78)
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: 18446744069414584320
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Il2CppInspector.Il2CppBinary.Configure(IFileFormatReader image, UInt64 codeRegistration, UInt64 metadataRegistration)
   at Il2CppInspector.Il2CppBinary.Initialize(Double version, UInt32 imageIndex)
   at Il2CppInspector.Il2CppBinary.Load(IFileFormatReader stream, Double metadataVersion)
   at Il2CppInspector.Il2CppInspector.LoadFromStream(Stream binaryStream, Stream metadataStream)
   at Il2CppInspector.Il2CppInspector.LoadFromFile(String binaryFile, String metadataFile)
   at Il2CppInspector.CLI.App.Run(Options options)
   at Il2CppInspector.CLI.App.<>c.<Main>b__2_0(Options options)
   at CommandLine.ParserResultExtensions.MapResult[TSource,TResult](ParserResult`1 result, Func`2 parsedFunc, Func`2 notParsedFunc)
   at Il2CppInspector.CLI.App.Main(String[] args)
Analyze IL2CPP data: 11.65 sec
```

**Comment by djkaty** [comment]
The binary file is malformed. `readelf -e` shows all sections are null. IDA complains that the file structure is bad and had illegal section values. Even though Il2CppInspector does correctly load the metadata structures from the binary, the addresses they point to do not contain the expected data. This is not a valid ELF binary I'm afraid.

Closing issue; feel free to comment if you believe this to be in error.

**Comment by kttyb0f** [comment]
Despite IDA's complaints, it loads it fine. Tested on 7.5 and 7.0, 269076 functions after analysis completes.

The root cause in reality is that they've rotated the definition of struct Il2CppMetadataRegistration (& code) - so offsets of struct members need to be reversed from the various il2cpp engine accessors. After reversing this and fixing the struct definition, il2cppdumper works, but I didn't try to fix this project yet.

As packers and obfuscation get more popular over time, maybe there could be some functionality to support this? Perhaps more versioned parser classes, and then in this kind of case you'd just need to write your own versioned parser to resolve the scrambled struct by pattern scanning. Anything is better than having to keep a whole separate clone/fork for each il2cpp target :p

**Comment by djkaty** [comment]
If I understand correctly, by "rotated" you're saying they arbitrarily re-defined the order of fields in Il2CppMetadata/CodeRegistration? If so, interesting, never seen that before. I looked at what Il2CppInspector was reading in the debugger, that would make sense, I didn't think of it at the time.

Bypassing encryption and obfuscation is generally beyond the scope of this project, but I did try to design Il2CppInspector to be more modular and extensible, so out of interest, how would you implement such a feature?

**Comment by kttyb0f** [comment]
It's a tough problem for sure. If we have to accept that the unity structures are mutable, and support plugins/classes "hooking" common code/metadatareg accessors... 

* I'm thinking the structures need to be user-definable in either a JSON format, or pseudo-C format with a small C parser library to turn that text into something the code can work with. I'd imagine the latter just for user-friendliness. This would necessitate a change to MetadataClasses.cs and any usage of those.
* I see developers do things like replace MetadataCache::GetStringFromIndex with some custom xor pad. So it's kind of necessary to allow a plugin to hook the project's equivalent.
* Il2CppBinary::Configure definitely could use some more significant validation logic to detect scenarios where the structures don't match up. Of course it can't be perfect, but some heuristics like: methodPointers really should be a contiguous array of pointers into the module; all of the *Count variables statistically follow a pattern if you've looked at many il2cpp samples - i.e. methodPointersCount > reversePInvokeWrapperPointersCount, methodPointersCount > unresolvedVirtualMethodPointersCount, I'd bet there's even more interesting correlations if we were to dump these counts for a significant corpus of il2cpp binaries.

I'm more on the cpp side than I am c# so I'm not too sure what the C#-idiomatic way would be to do most of these things.

**Comment by djkaty** [comment]
I need to think about it more but what springs immediately to mind is a feature not present in C++ - and that is to use attributes on the codereg/metadatareg structures in C# which would specify the offset eg:

```cs
public class Il2CppMetadataRegistration
    {
        public long genericClassesCount;
        [Offset=0x38]
        public ulong genericClasses;
        [Offset=0x20]
        public long genericInstsCount;
        public ulong genericInsts;
        public long genericMethodTableCount;
...
```

`Bin2Object` is a thin wrapper over reading streams that I implemented which provides the `Version` attribute and a couple of others you may see, to eliminate the need to have a version of the struct for every version of IL2CPP. I could definitely add the ability to process an Offset attribute to allow an arbitrary layout of any type. This would still require the user to edit the file of course, but .NET does offer an API to load text at runtime and compile it, so that could be an option for storing in an external file.

All of this is probably a fair amount of over-engineering for the scope of the problem though. Funnily enough I literally today just finished writing the code to parse all the C++ of the Unity headers to make field sizes and offsets in all the C++ types generated for use by the application available as an API, so the parser library you just described will actually be at our disposal in a few commits' time.

Set accessors is another option; the user would have to make function calls I suppose to set the offset of each field, and from then on using the get accessors would map them to the desired offsets.

I will say that I'm not going to do anything about this problem now as it's not something I've come across before (or had any other issues opened about) and it is essentially trivial to re-order the fields in Metadata/BinaryClasses.cs and re-compile. I do realize that's not ideal and the issue of having multiple forks for different targets is what you wanted to avoid, but I have to balance time spent vs usefulness. If this starts becoming common, I will obviously revisit the topic.

Thanks for your thoughts!

**Comment by djkaty** [comment]
Handling this scenario has now been added to the roadmap.

**Comment by djkaty** [comment]
This scenario is now resolved automatically in the latest series of commits.

See: https://github.com/djkaty/Il2CppInspector/blob/master/Il2CppInspector.Common/IL2CPP/ReconstructMetadata.cs

**Comment by kttyb0f** [comment]
Saw your wild rift article ;) Nice job! Love the heuristic you implemented. 

I do wish it wasn't easier for the average paster in WR now, though, haha. Hopefully they get stuck on the other things in libefeproj!

**Comment by djkaty** [comment]
Wow you were fast, I only posted it a few hours ago!

There are several downsides to posting such code and I'm often torn about it. On the one hand, the hackers who are trying to keep secrets hate you, the game companies hate you, the games get patched, and I don't particularly enjoy enabling script kiddies (I realize automated tools do that, but for me it's a labour of love). On the other hand, posting such code disables people who are trying to sell hacks for money, empowers people to develop their own skills (you and I have both read tons of reverse engineering articles made by other kind souls in our journeys right?), teaches the protection authors what they've done wrong, and helps democratize access to information since it's not really a great situation in the long-run if only a tiny number of people know how to solve a particular problem.

I'm sure the game will get patched and the merry-go-round will continue. Glad you enjoyed the code though ❤
