### ISSUE TITLE
Question: is it expected that generated methods are empty?

### ISSUE THREAD

**Issue by vivalavladislav** [djkaty/Il2CppInspector#49]
Hey, so I've recently decompiled one of the project of interest. The types and declarations are fine, but all the method implementations are empty. Is this expected?

**Comment by djkaty** [comment]
That's expected behaviour yes, the tool is not a decompiler, it only generates code stubs so you can navigate around the project layout with your IDE of choice, or compile it and use an IL viewer (there are still some edge case issues causing compile errors but there are vastly less than a few months ago).
