### ISSUE TITLE
Application crashes

### ISSUE THREAD

**Issue by bqio** [djkaty/Il2CppInspector#55]
After opening the metadata file and prx file, I get a freeze at this point and the application crashes.

![Screenshot_5](https://user-images.githubusercontent.com/45086516/89401495-6ddab400-d726-11ea-88ab-325fb810bdf0.png)

**Comment by xiaoxiao921** [comment]
I had the same issue with the already built releases, but I got it working by building the project myself

**Comment by djkaty** [comment]
Can you guys attach the files you were using that caused the crashes so I can take a look? :)

**Comment by bqio** [comment]
> Can you guys attach the files you were using that caused the crashes so I can take a look? :)

[data.zip](https://github.com/djkaty/Il2CppInspector/files/5029824/data.zip)

**Comment by djkaty** [comment]
I wasn't able to re-produce this problem with the GUI version with either the current latest commit, the 2020.1 release or a re-build of the 2020.1 release commit. I'm running Windows 10 64-bit. In all cases the files you sent were analysed just fine.

Have you tried building from the latest commit as @xiaoxiao921 suggested? There have been a lot of improvements and bug fixes since 2020.1 and we're nearing the release of 2020.2 in the next couple of weeks.

**Comment by bqio** [comment]
SOLVED!

Build latest version from source.

**Comment by djkaty** [comment]
Alright, I guess it's some obscure bug in the current release then. Glad you got it working! 2020.2 will hopefully be out in a couple weeks so you can use the pre-compiled binary then if you prefer.
