### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by kotori2** [djkaty/Il2CppInspector#57]
I came across some error with Python3.
![image](https://user-images.githubusercontent.com/17663689/90505214-d002d280-e184-11ea-997d-8986ee404444.png)

logs:
```
Generated script file by Il2CppInspector - http://www.djkaty.com - https://github.com/djkaty
Processing Types
Error .\il2cpp.h:1288: Type 'Boolean' is already defined
Error .\il2cpp.h:1378: Type 'UInt16' is already defined
Error .\il2cpp.h:1388: Type 'UInt32' is already defined
Error .\il2cpp.h:1408: Type 'UInt64' is already defined
Error .\il2cpp.h:2548: Type 'BytePtr' is already defined
Error .\il2cpp.h:79295: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81134: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81135: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81137: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81139: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81141: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81142: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81144: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81146: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:81148: Syntax error near: }
Error .\il2cpp.h:84218: Type 'IOAsyncCallback' is already defined
Error .\il2cpp.h:84220: Syntax error near: }
Error .\il2cpp.h:86226: Type 'Component' is already defined
Error .\il2cpp.h:86290: Type 'Component' is already defined
Error .\il2cpp.h:86291: Syntax error near: }
Processing method definitions
```

**Comment by kotori2** [comment]
It seems that for Python3 you shouldn't encode the `str` to `bytes` before feeding to IDA API.

**Comment by djkaty** [comment]
I don't have IDA Pro 7.5 (or 7.4 with optional Python 3 support) so I have no way of testing a fix for this. If you can submit a PR which provides a fix that is also compatible with earlier versions of IDA using Python 2.7 that would be great.

Also I'd like to take a look at your metadata and binary files if I may, there should not be re-definitions of types in il2cpp.h because we perform name conflict checking and resolve it by adding suffix digits to the end of same-named types, so that looks like an unrelated bug I'd be interested to fix.

**Comment by djkaty** [comment]
Hey! Could you try the latest commit now fresh in IDA with Python 3 and let me know if it works? I've also added some reserved keywords to the symbol generation list.

**Comment by kotori2** [comment]
Seems working. This issue can be closed now.

**Comment by djkaty** [comment]
Excellent, thank you!
