### ISSUE TITLE
Preserve Attribute Properties

### ISSUE THREAD

**Issue by Skamiplan** [djkaty/Il2CppInspector#64]
Hey, this a wonderful tool with crazy abilities.
I have a question though when extracting code from a binary file it does seem to preserve the attribute type but it loses the properties that are giving to it.

The result I'm getting; 

```
		[Json] // 0x10085A70-0x10085AA0
		public string LandingPageUrl; // 0x38
```
However, I'm expecting

```
		[Json(PropertyName = "u")] // 0x10085A70-0x10085AA0 or [Json("u")]
		public string LandingPageUrl; // 0x38
```
Just wondering if it is at all possible what I'm expecting.

PS.

Il2CppDumper generates the following

```
        [Attribute(Name="JsonAttribute", RVA="0x85A70", Offset="0x84E70")]
        [FieldOffset(Offset="0x38")]
        [Token(Token="0x400602D")]
        public string LandingPageUrl;
```

**Comment by djkaty** [comment]
Deriving constructor arguments for attributes automatically is much more difficult than most of the other information because the arguments are not encoded as metadata - rather, they are generated as C++ methods.

For example, in your above example you show an attribute with one string argument. Here is `DebuggerDisplay` (on `System.AggregateException`) transpiled to C++:

```cpp
static void AggregateException_t9217B9E89DF820D5632411F2BD92F444B17BD60E_CustomAttributesCacheGenerator(CustomAttributesCache* cache)
{
	{
		DebuggerDisplayAttribute_t4217FA369BB3F9B415423539B4A08882480836A0 * tmp = (DebuggerDisplayAttribute_t4217FA369BB3F9B415423539B4A08882480836A0 *)cache->attributes[0];
		DebuggerDisplayAttribute__ctor_m31F6CB042E520591E9DD2CA8ABC18F2D3189F6D0(tmp, il2cpp_codegen_string_new_wrapper("\x43\x6F\x75\x6E\x74\x20\x3D\x20\x7B\x49\x6E\x6E\x65\x72\x45\x78\x63\x65\x70\x74\x69\x6F\x6E\x43\x6F\x75\x6E\x74\x7D"), NULL);
	}
}
```

and here is how it looks in assembly:

```
.text:000000000039D674 ; void __fastcall DebuggerDisplayAttribute_CustomAttributesCacheGenerator_3790452(CustomAttributesCache *)
.text:000000000039D674 DebuggerDisplayAttribute_CustomAttributesCacheGenerator_3790452
.text:000000000039D674                                         ; DATA XREF: .data.rel.ro:0000000000F60580↓o
.text:000000000039D674
.text:000000000039D674 var_10          = -0x10
.text:000000000039D674 var_s0          =  0
.text:000000000039D674
.text:000000000039D674 ; __unwind {
.text:000000000039D674                 STR             X19, [SP,#-0x10+var_10]!
.text:000000000039D678                 STP             X29, X30, [SP,#0x10+var_s0]
.text:000000000039D67C                 ADD             X29, SP, #0x10
.text:000000000039D680                 LDR             X8, [X0,#8]
.text:000000000039D684                 ADRP            X0, #aCountInnerexce@PAGE ; "Count = {InnerExceptionCount}"
.text:000000000039D688                 ADD             X0, X0, #aCountInnerexce@PAGEOFF ; "Count = {InnerExceptionCount}"
.text:000000000039D68C                 LDR             X19, [X8]
.text:000000000039D690                 BL              j_il2cpp_string_new_wrapper_0
.text:000000000039D694                 LDP             X29, X30, [SP,#0x10+var_s0]
.text:000000000039D698                 MOV             X1, X0  ; value
.text:000000000039D69C                 MOV             X0, X19 ; this
.text:000000000039D6A0                 MOV             X2, XZR ; method
.text:000000000039D6A4                 LDR             X19, [SP+0x10+var_10],#0x20
.text:000000000039D6A8                 B               DebuggerDisplayAttribute__ctor
.text:000000000039D6A8 ; } // starts at 39D674
.text:000000000039D6A8 ; End of function DebuggerDisplayAttribute_CustomAttributesCacheGenerator_3790452
```

If you know what you're looking for with a particular attribute, it's fairly trivial to read the disassembly by hand and determine the arguments (the values after the comments give the virtual address of the function which calls the constructor).

The commit https://github.com/djkaty/Il2CppProtoExtractor-FallGuys/commit/21d1fb03933c75766f4d354e002ab97c9bb327ff shows how to use Capstone to iterate the disassembly and find the argument for a constructor when it is known to be a single integer, while also ignoring any other attributes initialized by the function (one attribute function calls attribute constructors for all of the attributes on the specific type or method the function applies to). (this commit is not documented in the written tutorial for that repo).

I elaborated a little bit on this problem and why the solution isn't implemented here: https://github.com/djkaty/Il2CppInspector/issues/59#issuecomment-678681736

This is something that is on the provisional todo-list and I may implement it in the future. It is likely to be an approximate/imperfect/incomplete solution. In the meantime, you might be able to adapt the example in the above commit to your needs if you know roughly what you're looking for.

Hope that helps explain!

**Comment by Skamiplan** [comment]
Thanks for the detailed response, especially this part helps a bunch

> (the values after the comments give the virtual address of the function which calls the constructor).

Not entirely sure how I missed that part.
Looking forward to future releases.

**Comment by djkaty** [comment]
You're welcome! 🙂
