### ISSUE TITLE
Il2cppExceptions definition missing & no Il2CppExceptionWrapper

### ISSUE THREAD

**Issue by DannyParker0001** [djkaty/Il2CppInspector#79]
I'm currently working on a program with Unity 2019.4.1.

Took a while to figure out, but code we were calling was throwing an exception, I believe for the exception to be successfully thrown, you need a managed thread, otherwise you'll just just get an access violation.
To achieve that, you just needed to put `Il2CppThread* thread = il2cpp_thread_attach(il2cpp_domain_get());` before you call your method. No need to actually use it. (It sets some static stuff I think)

Now any debugger will tell you a `Il2CppExceptionWrapper` has been thrown. From [this unity doc](https://docs.unity3d.com/Manual/windowsstore-debugging-il2cpp.html), the struct is:
```cpp
struct Il2CppExceptionWrapper
{
    Il2CppException* ex;

    Il2CppExceptionWrapper(Il2CppException* ex) : ex(ex) {}
};
```
This requires the `Il2CppException` struct to be defined. Once added, you can do something like this:
```cpp
try{
    // il2cpp_thread_attachstuff
    // method call
    //...
}catch (Il2CppExceptionWrapper e) {
    std::wcout << L"Il2cppException occurred:" << (wchar_t*)(e.ex->message->chars) << std::endl;
}
```
Current headers only have a forward declaration of the Il2cppException, not the definition. Would be great if you also added the Il2CppExceptionWrapper to the headers as well.

**Comment by DannyParker0001** [comment]
I'd like to add that  `Il2CppThread* thread = il2cpp_thread_attach(il2cpp_domain_get());` should probably go into `il2cpp-init.cpp`. As far as I can tell, it doesn't have any negative side effects, and should help future people out.

**Comment by djkaty** [comment]
Okay, took a look over the IL2CPP source code. Yes, I will apply these changes and a couple of related ones as soon as I have a bit of time!

**Comment by djkaty** [comment]
I've been working on this for a while; the reason the change is not made yet is because I want to integrate **all** of the IL2CPP internal versions of .NET types and ensure their formats are correct for every version of IL2CPP, not just add one or two like `Il2CppException` in piecemeal fashion here and there.

You can follow this in the companion repository at https://github.com/nneonneo/Il2CppVersions/pull/10

I've finished testing this now but will wait until Robert approves my PR in case any changes need to be made that would affect the header files before committing them to Il2CppInspector.

**Comment by djkaty** [comment]
This issue is resolved in https://github.com/djkaty/Il2CppInspector/commit/76825f231b6fd55c63976655052ead419dae292d

I'm going to close the issue but please could you leave a message indicating whether it works to your satisfaction :) Thanks!
