### ISSUE TITLE
PE section lengths and PEReader.MapVATR

### ISSUE THREAD

**Issue by zeobviouslyfakeacc** [djkaty/Il2CppInspector#8]
Hi!

First of all, thanks for this awesome project! After some code modifications and hardcoding the code and metadata offsets, I was able to extract the type information from a game with a 64-bit only PE (PE32+) GameAssembly.dll, which is incredibly useful.

However, I encountered some issues when reading the field offsets in Il2CppInspector ([here](https://github.com/djkaty/Il2CppInspector/blob/4e0f11bde4e696d7fda323593d560e9e63f19320/Il2CppInspector/Il2CppInspector.cs#L120-L130)).
Some values of `pFieldOffsets` pointed to memory locations in the .data section outside the [BaseMemory, BaseMemory + SizeImage] range, but inside the [BaseMemory, BaseMemory + SizeMemory] range. For these field offsets, an exception was thrown in PEReader.MapVATR, and I think this could also affect the supported 32-bit PE binaries.

Example:

| Name  | Offset |
| ------------- | ------------- |
| pFieldOffsets | 0x1_83A4_4460 |
| .data BaseMemory | 0x1_837E_1000 |
| .data BaseMemory + SizeImage | 0x1_839C_0C00 |
| .data BaseMemory + SizeMemory | 0x1_83CF_9148 |

According to this [PE format specification](https://docs.microsoft.com/en-us/windows/win32/debug/pe-format#section-table-section-headers), these memory locations between BaseMemory + SizeImage and BaseMemory + SizeMemory should be filled with zeros by the linker:
> VirtualSize [SizeMemory]: The total size of the section when loaded into memory. If this value is greater than SizeOfRawData [SizeImage], the section is zero-padded. This field is valid only for executable images and should be set to zero for object files.

I first tried just using `SizeMemory` instead of `SizeImage` inside `PEReader.MapVATR`, but obviously this doesn't fix the issue, as we just get back an offset to some unrelated location in the DLL file, outside the .data section.

Would it be possible to somehow detect such a read to an "always zero" memory region and fill the `offsets` Dictionary with zeros for these fields?

**Comment by djkaty** [comment]
Hey there,

Thanks for the detailed problem report. In the last couple weeks I added 64-bit file format support for Mach-O and ELF but I haven't started on PE32+ yet. MapVATR for those formats had the same bug which I resolved for those.

Please could you supply a sample (GameAssembly.dll and global-metadata.dat) for me to work through? Thanks!

**Comment by zeobviouslyfakeacc** [comment]
Sure, here you go! EmptyProjectData contains the assembly, PDB, and metadata from an empty Unity project that I compiled with IL2CPP, ActualGameData contains an assembly and metadata from a released game.

What tripped me up was that the empty project contained a function `s_Il2CppCodegenRegistration` (at `.text:00000001800D6C60`) that first loads the addresses of the CodeGenOptions, MetadataRegistration, and CodeRegistration; and then calls `il2cpp::vm::MetadataCache::Register` (at `.text:0000000180015AA0`).

However, in the actual-game GameAssembly.dll, there is only one of these two functions, at `.text:00000001802C3D20`. I assume that `il2cpp::vm::MetadataCache::Register` got inlined into `s_Il2CppCodegenRegistration` there. That really messed me up when I was looking for the CodeRegistration and MetadataRegistration offsets 😄 


[EmptyProjectData.zip](https://github.com/djkaty/Il2CppInspector/files/3776871/EmptyProjectData.zip)
[ActualGameData.zip](https://github.com/djkaty/Il2CppInspector/files/3776888/ActualGameData.zip)

**Comment by djkaty** [comment]
Alright, I've had a look at the files in IDA, I would definitely concur that `s_Il2CppCodegenRegistration` was inlined into `il2cpp::vm::MetadataCache::Register` in the production code. I've never actually seen that before, but looking over the il2cpp source code I note that `il2cpp_codegen_register` (in `il2cpp-codegen.h` or `il2cpp-codegen-il2cpp.h` depending which version you look at) is marked with `inline` in some versions (Unity 5.6.2p3, 5.6.4f1 and 2017.2.f3 have it; 2019.2.8f1 does not). I guess it just gets ignored normally.


`Il2CppCodegenRegistration(void)` is sometimes included in the file's initializer function list and sometimes not. In the latter case, the code in Il2CppInspector will try to find the initializer function which references it. These can be found at `.text:00000001800019D0` in the empty project and `.text:0000000180002380` in the production game. The latter is once again inlined, which again, I've never seen before.

I don't currently have support baked in for PE32+ or x64, but since I added ELF64 and ARMv8/A64 lately these are naturally on the todo list. You've provided some good samples here so I'll be happy to add support and think of a way of dealing with the inlining (probably just taking the first `lea` instructions as a first attempt).

This is going to take a while 😂

**Comment by djkaty** [comment]
Provisional support for PE32+ is added in commit https://github.com/djkaty/Il2CppInspector/commit/1496bbb623bab7e885a0767376dad961ae9e6596 (no fix for MapVATR yet)

**Comment by djkaty** [comment]
Provisional support for x64 is added in commit https://github.com/djkaty/Il2CppInspector/commit/b46565e833d830b2ab0a80a8c2b3c89dcd55968d

I also updated the Powershell script to generate x64 il2cpp binaries from a given .cs file.

The field offset problem is very strange and shouldn't be like that - the field offsets must be stored in the file somewhere and readable on startup. Even IDA places the field offset labels in a non-allocated area of virtual memory, ruling out the possibility of relocations being the issue. For the time being, the only reasonable workaround I see is to just catch the exception from `MapVATR` when the field offset data is read and use zeroes when an exception is thrown, basically like your original suggestion.

**Comment by djkaty** [comment]
Issue resolved in commit https://github.com/djkaty/Il2CppInspector/commit/98f18c009825b2fe589d24b02a43d17d2e3a0a4c

Please let me know if you have any further problems!

**Comment by zeobviouslyfakeacc** [comment]
Awesome! Thank you so much!
Confirmed working with the next version of the game I sent you 😄
This will seriously make reverse engineering 64-bit Unity games so much more accessible 🎉

**Comment by djkaty** [comment]
Thanks! I've been a busy bee on this project lately, got a ton of stuff to add so I hope it helps you :)
