### ISSUE TITLE
Il2CppInspector not getting correct addresses?

### ISSUE THREAD

**Issue by jakecrowley** [djkaty/Il2CppInspector#81]
Hi, I apologize in advance for anything stupid I might be doing, I am new to il2cpp stuff.. Anyway, I wrote this simple test code to try and read a field from the Player class.

```
void Run()
{
	// If you would like to write to a log file, specify the name above and use LogWrite()
	// LogWrite("Startup");

	// If you would like to output to a new console window, use NewConsole() to open one and redirect stdout
	NewConsole();

	auto LocalPlayer = PlayerControl__TypeInfo->static_fields->LocalPlayer;
	auto numEmergencies = LocalPlayer->fields.RemainingEmergencies;

	std::cout << "Num Emergencies Left: " << numEmergencies;
}
```

While trying to access the static_fields struct of any given class, I am getting garbage data, as shown in the screenshots below, where I set a breakpoint on the last line.

![image](https://user-images.githubusercontent.com/8465805/93940066-dba06680-fcf9-11ea-96ce-bc648a8afb66.png)

 Maybe the il2cpp_init function is not receiving the correct addresses for these classes?

**Comment by jakecrowley** [comment]
It is a 32 bit application, possibly something to do with this https://github.com/djkaty/Il2CppInspector/issues/25 ?

**Comment by djkaty** [comment]
Are you using the latest release or the latest build? The TypeInfo variables were changed to double-indirected pointers (as indicated in the current README), so you need to do `(*PlayerControl__TypeInfo)->static_fields` etc. The reason for this change is because not all of the TypeInfo addresses may be available at initialization time, so we are now using the address where the initialized pointer for each type will be stored once it is available.

If you have followed some documentation that is out of date, please let me know so I can update it!

**Comment by jakecrowley** [comment]
I'm using the latest release, I'll compile from source to see if that fixes it.

**Comment by djkaty** [comment]
Yeah I recommend you use the latest commit where the `__TypeInfo` variables have changed from `Il2CppClass *` to `Il2CppClass **`.

**Comment by jakecrowley** [comment]
Unrelated to the current problem, but I am having trouble building the project, "The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1.". I assume that is a problem with my .NET sdk installation.

**Comment by jakecrowley** [comment]
Updating to the most recent commit worked!

**Comment by djkaty** [comment]
Awesome!
