### ISSUE TITLE
Improving C++ export

### ISSUE THREAD

**Issue by JABirchall** [djkaty/Il2CppInspector#85]
A few questions and suggestions.

A) Since we have the namespaces and structures used to export C# tree structure, would this be possible to do for the C++ export. I've tried doing a small little project for a game and reading the il2cpp_types.h file is hard to find what im looking for. I have to refer to the c# export to find what im looking for. 

B) Would it be possible to use C++/CLR for interacting with the unity app, since they are C# types it would make sense to resolve C# types to C++/CLR types, this could also help with (A) Since for example 

`public Dictionary<int, HeroRatingData> HeroRatingByHeroTypeId;` in C# 
is exported as
`struct Dictionary_2_System_Int32_SharedModel_Meta_HeroesRating_HeroRatingData_ *HeroRatingByHeroTypeId;` in C++
This would also decrease file the export size since for these generic types would need to be all be generated seperatly

C) How do I call a internal class function?

**Comment by djkaty** [comment]
(A) is on the roadmap (see https://github.com/djkaty/Il2CppInspector/issues/37), although it will require a new module because neither IDA nor Ghidra will process C++ type definitions properly, which is why it currently is the way it is. Right now referring to the C# type output is the recommended way to find what you need, so you're "doing it right" 🙂

(B) You can make a wrapper and that's something that could be done in the future, but once compiled they are not C# types, they are loose C functions, and many of the idioms you might expect to work such as operator overloading will not - you have to use internal il2cpp calls for that. To make it work seamlessly like a C# application will require a lot of work. This is basically a minefield I don't have time to work on in the foreseeable future. PRs are always welcome!

(C) Not quite sure I understand the question? Visibility scope (public/private etc.) modifiers are lost when the code is compiled so you can call any function the same way.

**Comment by JABirchall** [comment]
A) Nice, look forward to it. But i still need to look at the .h file to see the types are in C++

B) thats what im doing atm. Just wondering if it was possible.

C) So since the game im working on uses a lot of dictionary<> types, I need to use the dictionary functions to view/add/remove/edit what the dictionary contains.

![](https://i.imgur.com/SHCIwv2.png)

I want to call getValues() on these dictionaries to see what they contain, and possibly do stuff to the values.

**Comment by djkaty** [comment]
Forewarning: I write the tool, I mostly don't use the tool - at least, not in the way other people do, because now I just code it for the community's requested features, it goes far beyond what I ever originally needed it for at this point 🙂

That being said, I believe what you need to do is access the VirtualInvokeData you want for your instance,  so first:

```cpp
auto vtableMethod = myInstance->vtable->System_Collections_IDictionary_get_values;
```

`VirtualInvokeData` contains two pointers: `methodPtr` is the function address in the binary, and `method` contains the `MethodInfo` pointer which indicates the concrete (specialized) method definition needed. You'll need to cast `methodPtr` to be a function pointer with the correct signature, eg.

```cpp
auto vtableMethodPtr = (Dictionary_2_TKey_TValue_ValueCollection_System_Object_System_Object_ (*)(Dictionary_2_System_Object_System_Object_ *this, MethodInfo *method)) vtableMethod.methodPtr;
```

(syntax might be a bit wrong, my C++ is rusty; I assume the correct way is to use `dynamic_cast` with a `typeid()` so that you don't need to know the concrete type in advance but that's a bit beyond my 10-year old knowledge of C++ - https://blog.panicsoftware.com/dynamic_cast-and-typeid-as-non-rtti-tools/ )

Then call it as follows:

```cpp
auto returnValue = (*vtableMethodPtr)(myInstance, vtableMethod.method);
```

Couple of notes:

1. I know this is a mess. You are currently using the inaugural version of the C++ scaffolding code and the primary objective was just to make it work at all :) There is a TODO in the code to produce typed versions of `VirtualInvokeData` where `methodPtr` is defined as a strongly typed function pointer so that casts can be avoided. Since this will require thousands of new struct types it will bloat the output significantly, it will get done eventually though.

2. If you know the concrete type you're working with at compile-time you can just call the function you need directly (`appdata/il2cpp-functions.h`) afaik.

I'm fumbling in the dark here but I hope that at least helps a little bit or points in the right direction!

**Comment by JABirchall** [comment]
I see, I think i found a function I need to call with the dictionary a parameter in il2cpp-functions.h

Which is this 
```
DO_APP_FUNC(0x00FC2A00, Dictionary_2_TKey_TValue_ValueCollection_System_Int32_SharedModel_Meta_Heroes_Hero_ *, Dictionary_2_System_Int32_SharedModel_Meta_Heroes_Hero__get_Values, (Dictionary_2_System_Int32_SharedModel_Meta_Heroes_Hero_ * __this, MethodInfo * method));
```

So, I think I should be able to call it like this (Its not pretty 😢 )
```
Dictionary_2_TKey_TValue_ValueCollection_System_Int32_SharedModel_Meta_Heroes_Hero_ *hero = Dictionary_2_System_Int32_SharedModel_Meta_Heroes_Hero__get_Values(F(heroes).F(HeroData).HeroById, F(heroes).C(HeroData).VT(get_Values))
```
And other similar dictionary functions.

*Note, F() C() VT() and such are just helper macros i made to shorten down the call chain by automating the .klass, .fields, .vtable on everything.

**Comment by djkaty** [comment]
Does it work? :)

**Comment by JABirchall** [comment]
TBH I havnt tested it, I had errors in other places of my project.
Ive been researching around and found this project :  https://github.com/HerpDerpinstine/MelonLoader/

So im going to mess around with that at bit since its allows for native C# interfacing with il2cpp apps

**Comment by djkaty** [comment]
Ooh that looks interesting, would love to hear how you get on with that!

I'm going to write a crash course tutorial (at some point) about how to do all the common tasks with Il2cpp in the C++ project, I've made a note to include vtable stuff. It's very likely (actually, it's a certainty) that I'll do quite a lot of re-factoring and improvements to this whole area of Il2CppInspector. It's just one output module and it's the newest one so there's a lot of work ahead to make it 'pretty'. For now, as said, it was all about getting it to work at all 🙂

**Comment by djkaty** [comment]
Closing; suggestions are on the roadmap and notes made regarding this issue.
